version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    networks:
      - network
    restart: always

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-miniokey}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123secret}
    command: server /data --console-address ":9001"
    networks:
      - network
    restart: always

  backend:
    container_name: cloud-storage_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "7070:7070"
    networks:
      - network
    depends_on:
      - postgres
      - minio
    restart: always
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: miniokey
      MINIO_ROOT_PASSWORD: minio123secret
      MINIO_BUCKET_NAME: store-bucket
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - network
    restart: always
networks:
  network:
    driver: bridge