version: '3.8'
services:
#  app:
#    build: .
#    ports:
#      - "8081:8081"
#    depends_on:
#      - minio
#    environment:
#      - MINIO_URL=http://minio:9000
#      - MINIO_ACCESS_KEY=miniokey
#      - MINIO_SECRET_KEY=minio123secret
#      - MINIO_BUCKET_NAME=store-bucket

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: miniokey
      MINIO_ROOT_PASSWORD: minio123secret
    command: server /data --console-address ":9001"

volumes:
  minio_data:
